# Copyright (c) 2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

apiVersion: v1
kind: Pod
metadata:
  name: umsample-sender
spec:
  initContainers:
    - name: wait-for-um
      image: busybox
      command: ['sh', '-c', 'until nslookup umsample-umhost; do echo waiting for UM; sleep 2; done;']
  containers:
    - name: umsample-sender
      image: https://github.com/MelanieMonnereau/apama-um-correlator-sender-container
      ports:
        - containerPort: 15903
      command: ["correlator", "--config", "/apama_work/UMSample/um-connectivity.yaml", "--config", "/apama_work/UMSample/init-sender.yaml"]